Add coreutils to deps.  Add dep checking to eeprom config

diff --git a/picore-rpi-eeprom-config b/picore-rpi-eeprom-config
--- a/picore-rpi-eeprom-config
+++ b/picore-rpi-eeprom-config
@@ -2,14 +2,14 @@
 
 # piCore script to update Raspberry Pi4/5 boot EEPROM.
 
-usage() {
+function usage() {
 	echo "Usage:"
 	echo "$0 <options>"
 	echo ""
 	echo "The default firmware upgrade is from the critical firmware branch"
-	echo "  to override, set the FIRMWARE_RELEASE_STATUS environmen variable"
-	echo "  export FIRMWARE_RELEASE_STATUS=<default|latest>"
-   echo ""
+	echo "	to override, set the FIRMWARE_RELEASE_STATUS environmen variable"
+	echo "	export FIRMWARE_RELEASE_STATUS=<default|latest>"
+	echo ""
 	echo "----------------------------------------------"
 	echo ""
 	echo "rpi-eeprom-config options"
@@ -17,13 +17,47 @@ usage() {
 	exit
 }
 
-mount_boot_partition() {
-   BOOTPART="$(tc_autoscan 'bootcode.bin' 'f')"
-   BOOTDEV=${BOOTPART%%/*}
-   find_mountpoint "$BOOTDEV"
-   if [ -n "$MOUNTPOINT" ]; then
-      mount $MOUNTPOINT
-   fi
+function mount_boot_partition() {
+	BOOTPART="$(tc_autoscan 'bootcode.bin' 'f')"
+	BOOTDEV=${BOOTPART%%/*}
+	find_mountpoint "$BOOTDEV"
+	if [ -n "$MOUNTPOINT" ]; then
+		mount $MOUNTPOINT
+	fi
+}
+
+function load_deps() {
+	if [ ! -f ${PACKAGEDIR}/raspi-utils.tcz ]; then
+		echo "raspi-utils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/vcgencmd ]; then
+		tce-load -i raspi-utils.tcz
+	fi
+
+	if [ ! -f ${PACKAGEDIR}/pciutils.tcz ]; then
+		echo "pciutils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/lspci ]; then
+		tce-load -i pciutils.tcz
+	fi
+
+	[ -f ${PACKAGEDIR}/python3.11.tcz ] && PYTHON3PKG=python3.11.tcz
+	[ -f ${PACKAGEDIR}/python3.12.tcz ] && PYTHON3PKG=python3.12.tcz
+	if [ ! -f ${PACKAGEDIR}/$PYTHON3PKG ]; then
+		echo "python 3 extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/python3 ]; then
+		tce-load -i $PYTHON3PKG
+	fi
+
+	[ ! -x /usr/local/bin/python ] && sudo ln -s /usr/local/bin/python3 /usr/local/bin/python
+
+	if [ ! -f ${PACKAGEDIR}/coreutils.tcz ]; then
+		echo "coreutils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/sha256sum ]; then
+		tce-load -i coreutils.tcz
+	fi
 }
 
 OPTS=""
@@ -34,9 +68,22 @@ for A in $@; do
 	esac
 done
 
+load_deps
+
 if [ "$OPTS" != "" ]; then
 	#If No OPTS are present, then we don't need to mount to just display the current config
 	mount_boot_partition >/dev/null 2>&1
 fi
+
+[ -f ${PACKAGEDIR}/python3.11.tcz ] && PYTHON3PKG=python3.11.tcz
+[ -f ${PACKAGEDIR}/python3.12.tcz ] && PYTHON3PKG=python3.12.tcz
+if [ ! -f ${PACKAGEDIR}/$PYTHON3PKG ]; then
+	echo "python 3 extension is required for this tool"
+	exit 1
+elif [ ! -f /usr/local/bin/python3 ]; then
+	tce-load -i $PYTHON3PKG
+fi
+
+[ ! -x /usr/local/bin/python ] && sudo ln -s /usr/local/bin/python3 /usr/local/bin/python
 
 sudo -E rpi-eeprom-config $OPTS
diff --git a/picore-rpi-eeprom-update b/picore-rpi-eeprom-update
--- a/picore-rpi-eeprom-update
+++ b/picore-rpi-eeprom-update
@@ -9,7 +9,7 @@ PACKAGEDIR=/etc/sysconfig/tcedir/optional
 
 checknotroot
 
-update_ext() {
+function update_ext() {
 	WGET="busybox wget"
 	DIFF="busybox diff"
 	MD5="busybox md5sum"
@@ -25,11 +25,11 @@ update_ext() {
 	$WGET -q https://github.com/tinycorelinux/rpi-eeprom/releases/latest/download/rpi-eeprom.tcz.md5.txt -P /tmp
 	$DIFF -q /tmp/rpi-eeprom.tcz.md5.txt /etc/sysconfig/tcedir/optional/rpi-eeprom.tcz.md5.txt >/dev/null 2>&1
 	if [ $? -eq 0 ]; then
-	   echo "[ INFO ] Extension version Matches"
-   	exit 2
+		echo "[ INFO ] Extension version Matches"
+		exit 2
 	else
-	   echo "[ INFO ] Update Required."
-	   $WGET -q https://github.com/tinycorelinux/rpi-eeprom/releases/latest/download/rpi-eeprom.tcz -P /tmp
+		echo "[ INFO ] Update Required."
+		$WGET -q https://github.com/tinycorelinux/rpi-eeprom/releases/latest/download/rpi-eeprom.tcz -P /tmp
 	fi
 
 	cd /tmp
@@ -37,24 +37,24 @@ update_ext() {
 	$MD5 -cs rpi-eeprom.tcz.md5.txt
 	[ -d $UPGRADE_DIR ] || mkdir -p $UPGRADE_DIR
 	if [ $? -eq 0 ]; then
-	   mv -f /tmp/rpi-eeprom.tcz* ${UPGRADE_DIR}
+		mv -f /tmp/rpi-eeprom.tcz* ${UPGRADE_DIR}
 	else
-	   echo "[ERROR] rpi-eeprom.tcz failed md5 check."
-	   exit 1
+		echo "[ERROR] rpi-eeprom.tcz failed md5 check."
+		exit 1
 	fi
 
 	echo "[ INFO ] A reboot is needed to load new rpi-eeprom extension."
 	exit
 }
 
-usage() {
+function usage() {
 	echo "Usage:"
 	echo "$0 --update:   Update rpi-eeprom.tcz extension"
 	echo ""
 	echo "The default firmware upgrade is from the critical firmware branch"
 	echo "  to override, set the FIRMWARE_RELEASE_STATUS environmen variable"
 	echo "  export FIRMWARE_RELEASE_STATUS=<default|latest>"
-   echo ""
+	echo ""
 	echo "----------------------------------------------"
 	echo ""
 	echo "rpi-eeprom-update options"
@@ -62,12 +62,47 @@ usage() {
 	exit
 }
 
-mount_boot_partition() {
+function mount_boot_partition() {
 	BOOTPART="$(tc_autoscan 'bootcode.bin' 'f')"
 	BOOTDEV=${BOOTPART%%/*}
 	find_mountpoint "$BOOTDEV"
 	if [ -n "$MOUNTPOINT" ]; then
 		mount $MOUNTPOINT
+	fi
+}
+
+
+function load_deps() {
+	if [ ! -f ${PACKAGEDIR}/raspi-utils.tcz ]; then
+		echo "raspi-utils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/vcgencmd ]; then
+		tce-load -i raspi-utils.tcz
+	fi
+
+	if [ ! -f ${PACKAGEDIR}/pciutils.tcz ]; then
+		echo "pciutils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/lspci ]; then
+		tce-load -i pciutils.tcz
+	fi
+
+	[ -f ${PACKAGEDIR}/python3.11.tcz ] && PYTHON3PKG=python3.11.tcz
+	[ -f ${PACKAGEDIR}/python3.12.tcz ] && PYTHON3PKG=python3.12.tcz
+	if [ ! -f ${PACKAGEDIR}/$PYTHON3PKG ]; then
+		echo "python 3 extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/python3 ]; then
+		tce-load -i $PYTHON3PKG
+	fi
+
+	[ ! -x /usr/local/bin/python ] && sudo ln -s /usr/local/bin/python3 /usr/local/bin/python
+
+	if [ ! -f ${PACKAGEDIR}/coreutils.tcz ]; then
+		echo "coreutils extension is required for this tool"
+		exit 1
+	elif [ ! -f /usr/local/bin/sha256sum ]; then
+		tce-load -i coreutils.tcz
 	fi
 }
 
@@ -80,32 +115,9 @@ for A in $@; do
 	esac
 done
 
+load_deps
+
 mount_boot_partition >/dev/null 2>&1
-
-if [ ! -f ${PACKAGEDIR}/raspi-utils.tcz ]; then
-	echo "raspi-utils extension is required for this tool"
-	exit 1
-elif [ ! -f /usr/local/bin/vcgencmd ]; then
-	tce-load -i raspi-utils.tcz
-fi
-
-if [ ! -f ${PACKAGEDIR}/pciutils.tcz ]; then
-	echo "pciutils extension is required for this tool"
-	exit 1
-elif [ ! -f /usr/local/bin/lspci ]; then
-	tce-load -i pciutils.tcz
-fi
-
-[ -f ${PACKAGEDIR}/python3.11.tcz ] && PYTHON3PKG=python3.11.tcz
-[ -f ${PACKAGEDIR}/python3.12.tcz ] && PYTHON3PKG=python3.12.tcz
-if [ ! -f ${PACKAGEDIR}/$PYTHON3PKG ]; then
-	echo "python 3 extension is required for this tool"
-	exit 1
-elif [ ! -f /usr/local/bin/python3 ]; then
-	tce-load -i $PYTHON3PKG
-fi
-
-[ ! -x /usr/local/bin/python ] && sudo ln -s /usr/local/bin/python3 /usr/local/bin/python
 
 echo "piCore rpi-eeprom package version: $VERSION"
 sudo -E rpi-eeprom-update $OPTS
